-- Creates the models table (idempotent) and seeds the Default model
-- Safe to run multiple times; uses IF NOT EXISTS and ON CONFLICT DO NOTHING
BEGIN;

CREATE TABLE IF NOT EXISTS models (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    -- Economic parameters
    discount_rate DOUBLE PRECISION,
    inflation_rate DOUBLE PRECISION,
    electricity_escalation DOUBLE PRECISION,
    crop_escalation DOUBLE PRECISION,
    project_life INTEGER,
    -- Solar parameters (capacity_factor comes from PVWatts)
    land_intensity_acres_per_MW DOUBLE PRECISION,
    degradation_rate DOUBLE PRECISION,
    installed_cost_per_MW DOUBLE PRECISION,
    site_prep_cost_per_acre DOUBLE PRECISION,
    grading_cost_per_acre DOUBLE PRECISION,
    retilling_cost_per_acre DOUBLE PRECISION,
    interconnection_fraction DOUBLE PRECISION,
    bond_cost_per_acre DOUBLE PRECISION,
    vegetation_cost_per_acre DOUBLE PRECISION,
    insurance_cost_per_acre DOUBLE PRECISION,
    oandm_cost_per_kw DOUBLE PRECISION,
    replacement_cost_per_MW DOUBLE PRECISION,
    replacement_year INTEGER,
    decommission_cost_per_kw DOUBLE PRECISION,
    remediation_cost_per_acre DOUBLE PRECISION,
    salvage_value_per_acre DOUBLE PRECISION,
    availability_factor DOUBLE PRECISION,
    curtailment_factor DOUBLE PRECISION,
    export_factor DOUBLE PRECISION,
    -- Lease parameters
    lease_min_rate DOUBLE PRECISION,
    lease_max_rate DOUBLE PRECISION,
    lease_escalation_rate DOUBLE PRECISION,
    developer_retention_fraction DOUBLE PRECISION,
    -- Constraint parameters
    constraints_min_ag_fraction DOUBLE PRECISION,
    constraints_max_prime_solar DOUBLE PRECISION,
    constraints_zoning_max_solar DOUBLE PRECISION,
    constraints_setback_fraction DOUBLE PRECISION,
    constraints_easement_acres DOUBLE PRECISION,
    constraints_wetland_exclusion_acres DOUBLE PRECISION,
    constraints_interconnect_capacity_mw DOUBLE PRECISION,
    -- Farmer parameters
    farmer_pa116_credit_per_acre DOUBLE PRECISION,
    -- Equations metadata (optional editable list)
    equations JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO models (
    name,
    description,
    discount_rate,
    inflation_rate,
    electricity_escalation,
    crop_escalation,
    project_life,
    land_intensity_acres_per_MW,
    degradation_rate,
    installed_cost_per_MW,
    site_prep_cost_per_acre,
    grading_cost_per_acre,
    retilling_cost_per_acre,
    interconnection_fraction,
    bond_cost_per_acre,
    vegetation_cost_per_acre,
    insurance_cost_per_acre,
    oandm_cost_per_kw,
    replacement_cost_per_MW,
    replacement_year,
    decommission_cost_per_kw,
    remediation_cost_per_acre,
    salvage_value_per_acre,
    availability_factor,
    curtailment_factor,
    export_factor,
    lease_min_rate,
    lease_max_rate,
    lease_escalation_rate,
    developer_retention_fraction,
    constraints_min_ag_fraction,
    constraints_max_prime_solar,
    constraints_zoning_max_solar,
    constraints_setback_fraction,
    constraints_easement_acres,
    constraints_wetland_exclusion_acres,
    constraints_interconnect_capacity_mw,
    farmer_pa116_credit_per_acre,
    equations
)
VALUES (
    'Default',
    'Baseline parameters prior to user-defined overrides',
    0.08,
    0.02,
    0.02,
    0.00,
    27,
    5.5,
    0.005,
    1610000.0,
    36800.0,
    8286.0,
    950.0,
    0.30,
    10000.0,
    225.0,
    100.0,
    11.0,
    100000.0,
    14,
    400.0,
    2580.0,
    12500.0,
    0.98,
    0.95,
    1.0,
    NULL,
    NULL,
    0.0,
    0.12,
    0.51,
    40.0,
    40.0,
    0.10,
    0.0,
    0.0,
    10.0,
    0.0,
    '[
      {"title": "Solar CAPEX per acre", "eq": "CAPEX = (C_install / alpha) + C_site + C_grade + C_retill + C_bond + f_inter * (C_install / alpha)"},
      {"title": "Solar energy (year t)", "eq": "E_t = 8760 * CF * 1000 * (1 - d)^t * eta_avail * eta_curt * eta_export"},
      {"title": "Solar revenue (year t)", "eq": "Rev_t = (E_t / alpha) * P_elec * (1 + g_elec)^t"},
      {"title": "Solar NPV (no lease)", "eq": "NPV_solar = sum_{t=0..T} (Rev_t - Cost_t) / (1+r)^t"},
      {"title": "ITC benefit (year 2)", "eq": "ITC = CAPEX * itc_rate"},
      {"title": "Lease rate", "eq": "L = 0.88 * NPV_solar / sum_{t=1..T} 1/(1+r)^t"},
      {"title": "Crop PV per acre", "eq": "PV_crop = sum_{t=1..T} (yield * price_t - cost) / (1+r)^t"},
      {"title": "Objective (maximize)", "eq": "max z = PV_lease * A_s + sum_j PV_crop_j * A_cj"},
      {"title": "Coupling constraint", "eq": "A_s + sum A_cj = crop_land"},
      {"title": "Min agriculture", "eq": "sum A_cj >= 0.51 * total_land"},
      {"title": "Solar cap", "eq": "A_s <= min(usable, prime_cap, zoning_cap, interconnect * alpha)"}
    ]'::jsonb
)
ON CONFLICT (name) DO NOTHING;

COMMIT;
